export const quickGoalSuggestions = [
  'Morning Cooking',
  '50 Days of Breakfast',
  'Send Funds',
  'Read 10 Pages',
  'Drink More Water',
  'Daily Morning Walk',
  'Complete My Assignment',
  'Save ₦5,000',
  'Call My Parents',
  'Practice Coding',
  'Clean My Room',
  'Plan Tomorrow',
  'Wake Up Early',
  'Sleep Before Midnight',
  'Exercise for 30 Minutes',
  'Learn Something New',
  'Finish My Project',
  'Apply for a Job',
  'Update My Portfolio',
  'Reply to Important Messages',
  'Take My Vitamins',
  'Journal for 10 Minutes',
  'Meditate Before Work',
  'Review My Goals',
  'Practice Gratitude',
  'Cook Dinner',
  'Buy Groceries',
  'Do My Laundry',
  'Wash the Dishes',
  'Organize My Workspace',
  'Study for One Hour',
  'Revise Class Notes',
  'Complete One LeetCode Problem',
  'Build a Small Feature',
  'Fix One Bug',
  'Push My Code',
  'Review a Pull Request',
  'Learn TypeScript',
  'Practice React',
  'Study Backend Development',
  'Read Documentation',
  'Watch a Tutorial',
  'Write a Blog Post',
  'Post on LinkedIn',
  'Reach Out to a Client',
  'Send an Invoice',
  'Track My Expenses',
  'Save for a New Laptop',
  'Avoid Unnecessary Spending',
  'Pay My Bills',
  'Drink No Soda',
  'Eat More Fruit',
  'Prepare a Healthy Meal',
  'Stretch for 10 Minutes',
  'Do 20 Push-Ups',
  'Go for a Run',
  'Take a Screen Break',
  'Spend Less Time Online',
  'Limit Social Media',
  'Read Before Bed',
  'Practice Deep Breathing',
  'Take a Cold Shower',
  'Make My Bed',
  'Declutter One Drawer',
  'Clean My Shoes',
  'Plan My Week',
  'Set Monthly Goals',
  'Review My Budget',
  'Check My Calendar',
  'Prepare for Tomorrow',
  'Learn Five New Words',
  'Practice French',
  'Practice Yoruba',
  'Write 500 Words',
  'Sketch for 15 Minutes',
  'Practice Photography',
  'Listen to a Podcast',
  'Read One Article',
  'Finish One Chapter',
  'Call a Friend',
  'Check In on Someone',
  'Spend Time With Family',
  'Plan a Date',
  'Buy a Thoughtful Gift',
  'Send a Thank-You Message',
  'Pray in the Morning',
  'Attend Church',
  'Read My Bible',
  'Reflect Before Bed',
  'Be Kind to Someone',
  'Compliment Someone',
  'Help Someone Today',
  'Complete My Chores',
  'Water the Plants',
  'Take Out the Trash',
  'Wash My Car',
  'Prepare Breakfast',
  'Pack My Bag',
  'Charge My Devices',
  'Start the Day Strong',
];