/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GoalIndexRouteImport } from './routes/goal/index'
import { Route as ChillIndexRouteImport } from './routes/chill/index'
import { Route as AppWellnessRouteImport } from './routes/app/wellness'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppInsightsRouteImport } from './routes/app/insights'
import { Route as AppHomeRouteImport } from './routes/app/home'
import { Route as AppSubProfileSettingsRouteImport } from './routes/app/sub-profile/settings'
import { Route as AppSubProfileInsightsRouteImport } from './routes/app/sub-profile/insights'
import { Route as AppActionsFlexxRouteImport } from './routes/app/actions/flexx'
import { Route as ChillTimerSessionIdDurationRouteImport } from './routes/chill/timer.$sessionId.$duration'

const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalIndexRoute = GoalIndexRouteImport.update({
  id: '/goal/',
  path: '/goal/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChillIndexRoute = ChillIndexRouteImport.update({
  id: '/chill/',
  path: '/chill/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWellnessRoute = AppWellnessRouteImport.update({
  id: '/app/wellness',
  path: '/app/wellness',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/app/insights',
  path: '/app/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/app/home',
  path: '/app/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSubProfileSettingsRoute = AppSubProfileSettingsRouteImport.update({
  id: '/app/sub-profile/settings',
  path: '/app/sub-profile/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSubProfileInsightsRoute = AppSubProfileInsightsRouteImport.update({
  id: '/app/sub-profile/insights',
  path: '/app/sub-profile/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AppActionsFlexxRoute = AppActionsFlexxRouteImport.update({
  id: '/app/actions/flexx',
  path: '/app/actions/flexx',
  getParentRoute: () => rootRouteImport,
} as any)
const ChillTimerSessionIdDurationRoute =
  ChillTimerSessionIdDurationRouteImport.update({
    id: '/chill/timer/$sessionId/$duration',
    path: '/chill/timer/$sessionId/$duration',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/notifications': typeof NotificationsRoute
  '/app/home': typeof AppHomeRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/wellness': typeof AppWellnessRoute
  '/chill': typeof ChillIndexRoute
  '/goal': typeof GoalIndexRoute
  '/app/actions/flexx': typeof AppActionsFlexxRoute
  '/app/sub-profile/insights': typeof AppSubProfileInsightsRoute
  '/app/sub-profile/settings': typeof AppSubProfileSettingsRoute
  '/chill/timer/$sessionId/$duration': typeof ChillTimerSessionIdDurationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/notifications': typeof NotificationsRoute
  '/app/home': typeof AppHomeRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/wellness': typeof AppWellnessRoute
  '/chill': typeof ChillIndexRoute
  '/goal': typeof GoalIndexRoute
  '/app/actions/flexx': typeof AppActionsFlexxRoute
  '/app/sub-profile/insights': typeof AppSubProfileInsightsRoute
  '/app/sub-profile/settings': typeof AppSubProfileSettingsRoute
  '/chill/timer/$sessionId/$duration': typeof ChillTimerSessionIdDurationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/notifications': typeof NotificationsRoute
  '/app/home': typeof AppHomeRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/wellness': typeof AppWellnessRoute
  '/chill/': typeof ChillIndexRoute
  '/goal/': typeof GoalIndexRoute
  '/app/actions/flexx': typeof AppActionsFlexxRoute
  '/app/sub-profile/insights': typeof AppSubProfileInsightsRoute
  '/app/sub-profile/settings': typeof AppSubProfileSettingsRoute
  '/chill/timer/$sessionId/$duration': typeof ChillTimerSessionIdDurationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/notifications'
    | '/app/home'
    | '/app/insights'
    | '/app/profile'
    | '/app/wellness'
    | '/chill'
    | '/goal'
    | '/app/actions/flexx'
    | '/app/sub-profile/insights'
    | '/app/sub-profile/settings'
    | '/chill/timer/$sessionId/$duration'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/notifications'
    | '/app/home'
    | '/app/insights'
    | '/app/profile'
    | '/app/wellness'
    | '/chill'
    | '/goal'
    | '/app/actions/flexx'
    | '/app/sub-profile/insights'
    | '/app/sub-profile/settings'
    | '/chill/timer/$sessionId/$duration'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/notifications'
    | '/app/home'
    | '/app/insights'
    | '/app/profile'
    | '/app/wellness'
    | '/chill/'
    | '/goal/'
    | '/app/actions/flexx'
    | '/app/sub-profile/insights'
    | '/app/sub-profile/settings'
    | '/chill/timer/$sessionId/$duration'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  NotificationsRoute: typeof NotificationsRoute
  AppHomeRoute: typeof AppHomeRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppWellnessRoute: typeof AppWellnessRoute
  ChillIndexRoute: typeof ChillIndexRoute
  GoalIndexRoute: typeof GoalIndexRoute
  AppActionsFlexxRoute: typeof AppActionsFlexxRoute
  AppSubProfileInsightsRoute: typeof AppSubProfileInsightsRoute
  AppSubProfileSettingsRoute: typeof AppSubProfileSettingsRoute
  ChillTimerSessionIdDurationRoute: typeof ChillTimerSessionIdDurationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goal/': {
      id: '/goal/'
      path: '/goal'
      fullPath: '/goal'
      preLoaderRoute: typeof GoalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chill/': {
      id: '/chill/'
      path: '/chill'
      fullPath: '/chill'
      preLoaderRoute: typeof ChillIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/wellness': {
      id: '/app/wellness'
      path: '/app/wellness'
      fullPath: '/app/wellness'
      preLoaderRoute: typeof AppWellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/insights': {
      id: '/app/insights'
      path: '/app/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/home': {
      id: '/app/home'
      path: '/app/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/sub-profile/settings': {
      id: '/app/sub-profile/settings'
      path: '/app/sub-profile/settings'
      fullPath: '/app/sub-profile/settings'
      preLoaderRoute: typeof AppSubProfileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/sub-profile/insights': {
      id: '/app/sub-profile/insights'
      path: '/app/sub-profile/insights'
      fullPath: '/app/sub-profile/insights'
      preLoaderRoute: typeof AppSubProfileInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/actions/flexx': {
      id: '/app/actions/flexx'
      path: '/app/actions/flexx'
      fullPath: '/app/actions/flexx'
      preLoaderRoute: typeof AppActionsFlexxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chill/timer/$sessionId/$duration': {
      id: '/chill/timer/$sessionId/$duration'
      path: '/chill/timer/$sessionId/$duration'
      fullPath: '/chill/timer/$sessionId/$duration'
      preLoaderRoute: typeof ChillTimerSessionIdDurationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  NotificationsRoute: NotificationsRoute,
  AppHomeRoute: AppHomeRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppProfileRoute: AppProfileRoute,
  AppWellnessRoute: AppWellnessRoute,
  ChillIndexRoute: ChillIndexRoute,
  GoalIndexRoute: GoalIndexRoute,
  AppActionsFlexxRoute: AppActionsFlexxRoute,
  AppSubProfileInsightsRoute: AppSubProfileInsightsRoute,
  AppSubProfileSettingsRoute: AppSubProfileSettingsRoute,
  ChillTimerSessionIdDurationRoute: ChillTimerSessionIdDurationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
