/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GoalIndexRouteImport } from './routes/goal/index'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppInsightsRouteImport } from './routes/app/insights'
import { Route as AppHomeRouteImport } from './routes/app/home'
import { Route as AppSubProfileSettingsRouteImport } from './routes/app/sub-profile/settings'
import { Route as AppSubProfileInsightsRouteImport } from './routes/app/sub-profile/insights'
import { Route as AppActionsFlexxRouteImport } from './routes/app/actions/flexx'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalIndexRoute = GoalIndexRouteImport.update({
  id: '/goal/',
  path: '/goal/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/app/insights',
  path: '/app/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/app/home',
  path: '/app/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSubProfileSettingsRoute = AppSubProfileSettingsRouteImport.update({
  id: '/app/sub-profile/settings',
  path: '/app/sub-profile/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSubProfileInsightsRoute = AppSubProfileInsightsRouteImport.update({
  id: '/app/sub-profile/insights',
  path: '/app/sub-profile/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AppActionsFlexxRoute = AppActionsFlexxRouteImport.update({
  id: '/app/actions/flexx',
  path: '/app/actions/flexx',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/home': typeof AppHomeRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/profile': typeof AppProfileRoute
  '/goal': typeof GoalIndexRoute
  '/app/actions/flexx': typeof AppActionsFlexxRoute
  '/app/sub-profile/insights': typeof AppSubProfileInsightsRoute
  '/app/sub-profile/settings': typeof AppSubProfileSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/home': typeof AppHomeRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/profile': typeof AppProfileRoute
  '/goal': typeof GoalIndexRoute
  '/app/actions/flexx': typeof AppActionsFlexxRoute
  '/app/sub-profile/insights': typeof AppSubProfileInsightsRoute
  '/app/sub-profile/settings': typeof AppSubProfileSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/home': typeof AppHomeRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/profile': typeof AppProfileRoute
  '/goal/': typeof GoalIndexRoute
  '/app/actions/flexx': typeof AppActionsFlexxRoute
  '/app/sub-profile/insights': typeof AppSubProfileInsightsRoute
  '/app/sub-profile/settings': typeof AppSubProfileSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/home'
    | '/app/insights'
    | '/app/profile'
    | '/goal'
    | '/app/actions/flexx'
    | '/app/sub-profile/insights'
    | '/app/sub-profile/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/home'
    | '/app/insights'
    | '/app/profile'
    | '/goal'
    | '/app/actions/flexx'
    | '/app/sub-profile/insights'
    | '/app/sub-profile/settings'
  id:
    | '__root__'
    | '/'
    | '/app/home'
    | '/app/insights'
    | '/app/profile'
    | '/goal/'
    | '/app/actions/flexx'
    | '/app/sub-profile/insights'
    | '/app/sub-profile/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppHomeRoute: typeof AppHomeRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppProfileRoute: typeof AppProfileRoute
  GoalIndexRoute: typeof GoalIndexRoute
  AppActionsFlexxRoute: typeof AppActionsFlexxRoute
  AppSubProfileInsightsRoute: typeof AppSubProfileInsightsRoute
  AppSubProfileSettingsRoute: typeof AppSubProfileSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goal/': {
      id: '/goal/'
      path: '/goal'
      fullPath: '/goal'
      preLoaderRoute: typeof GoalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/insights': {
      id: '/app/insights'
      path: '/app/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/home': {
      id: '/app/home'
      path: '/app/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/sub-profile/settings': {
      id: '/app/sub-profile/settings'
      path: '/app/sub-profile/settings'
      fullPath: '/app/sub-profile/settings'
      preLoaderRoute: typeof AppSubProfileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/sub-profile/insights': {
      id: '/app/sub-profile/insights'
      path: '/app/sub-profile/insights'
      fullPath: '/app/sub-profile/insights'
      preLoaderRoute: typeof AppSubProfileInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/actions/flexx': {
      id: '/app/actions/flexx'
      path: '/app/actions/flexx'
      fullPath: '/app/actions/flexx'
      preLoaderRoute: typeof AppActionsFlexxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppHomeRoute: AppHomeRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppProfileRoute: AppProfileRoute,
  GoalIndexRoute: GoalIndexRoute,
  AppActionsFlexxRoute: AppActionsFlexxRoute,
  AppSubProfileInsightsRoute: AppSubProfileInsightsRoute,
  AppSubProfileSettingsRoute: AppSubProfileSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
