/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AchievementSimulatorRouteImport } from './routes/achievement-simulator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JournalIndexRouteImport } from './routes/journal/index'
import { Route as GoalIndexRouteImport } from './routes/goal/index'
import { Route as ChillIndexRouteImport } from './routes/chill/index'
import { Route as JournalDateRouteImport } from './routes/journal/$date'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthConfirmRouteImport } from './routes/auth/confirm'
import { Route as AppWellnessRouteImport } from './routes/app/wellness'
import { Route as AppRewindHistoryRouteImport } from './routes/app/rewind-history'
import { Route as AppRewindRouteImport } from './routes/app/rewind'
import { Route as AppRewardsRouteImport } from './routes/app/rewards'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppLegalRouteImport } from './routes/app/legal'
import { Route as AppInsightsRouteImport } from './routes/app/insights'
import { Route as AppHomeRouteImport } from './routes/app/home'
import { Route as AppGoalRouteImport } from './routes/app/goal'
import { Route as AppCommunitiesRouteImport } from './routes/app/communities'
import { Route as AppUUsernameRouteImport } from './routes/app/u/$username'
import { Route as AppSubProfileSettingsRouteImport } from './routes/app/sub-profile/settings'
import { Route as AppSubProfileInsightsRouteImport } from './routes/app/sub-profile/insights'
import { Route as AppInviteCodeRouteImport } from './routes/app/invite.$code'
import { Route as AppCommunityCommunityIdRouteImport } from './routes/app/community/$communityId'
import { Route as AppCommunitiesMyRouteImport } from './routes/app/communities.my'
import { Route as AppAdminFeatureFlagsRouteImport } from './routes/app/admin.feature-flags'
import { Route as AppActionsFlexxRouteImport } from './routes/app/actions/flexx'
import { Route as ChillTimerSessionIdDurationRouteImport } from './routes/chill/timer.$sessionId.$duration'
import { Route as AppCommunityTemplatesTemplateIdRouteImport } from './routes/app/community/templates/$templateId'
import { Route as AppCommunityMembersCommunityIdRouteImport } from './routes/app/community/members/$communityId'
import { Route as AppCommunityGoalsCommunityIdRouteImport } from './routes/app/community/goals/$communityId'
import { Route as AppCommunityActivityCommunityIdRouteImport } from './routes/app/community/activity/$communityId'

const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementSimulatorRoute = AchievementSimulatorRouteImport.update({
  id: '/achievement-simulator',
  path: '/achievement-simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalIndexRoute = GoalIndexRouteImport.update({
  id: '/goal/',
  path: '/goal/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChillIndexRoute = ChillIndexRouteImport.update({
  id: '/chill/',
  path: '/chill/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalDateRoute = JournalDateRouteImport.update({
  id: '/journal/$date',
  path: '/journal/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWellnessRoute = AppWellnessRouteImport.update({
  id: '/app/wellness',
  path: '/app/wellness',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRewindHistoryRoute = AppRewindHistoryRouteImport.update({
  id: '/app/rewind-history',
  path: '/app/rewind-history',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRewindRoute = AppRewindRouteImport.update({
  id: '/app/rewind',
  path: '/app/rewind',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRewardsRoute = AppRewardsRouteImport.update({
  id: '/app/rewards',
  path: '/app/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLegalRoute = AppLegalRouteImport.update({
  id: '/app/legal',
  path: '/app/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/app/insights',
  path: '/app/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/app/home',
  path: '/app/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGoalRoute = AppGoalRouteImport.update({
  id: '/app/goal',
  path: '/app/goal',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCommunitiesRoute = AppCommunitiesRouteImport.update({
  id: '/app/communities',
  path: '/app/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUUsernameRoute = AppUUsernameRouteImport.update({
  id: '/app/u/$username',
  path: '/app/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSubProfileSettingsRoute = AppSubProfileSettingsRouteImport.update({
  id: '/app/sub-profile/settings',
  path: '/app/sub-profile/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSubProfileInsightsRoute = AppSubProfileInsightsRouteImport.update({
  id: '/app/sub-profile/insights',
  path: '/app/sub-profile/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInviteCodeRoute = AppInviteCodeRouteImport.update({
  id: '/app/invite/$code',
  path: '/app/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCommunityCommunityIdRoute = AppCommunityCommunityIdRouteImport.update({
  id: '/app/community/$communityId',
  path: '/app/community/$communityId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCommunitiesMyRoute = AppCommunitiesMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => AppCommunitiesRoute,
} as any)
const AppAdminFeatureFlagsRoute = AppAdminFeatureFlagsRouteImport.update({
  id: '/app/admin/feature-flags',
  path: '/app/admin/feature-flags',
  getParentRoute: () => rootRouteImport,
} as any)
const AppActionsFlexxRoute = AppActionsFlexxRouteImport.update({
  id: '/app/actions/flexx',
  path: '/app/actions/flexx',
  getParentRoute: () => rootRouteImport,
} as any)
const ChillTimerSessionIdDurationRoute =
  ChillTimerSessionIdDurationRouteImport.update({
    id: '/chill/timer/$sessionId/$duration',
    path: '/chill/timer/$sessionId/$duration',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppCommunityTemplatesTemplateIdRoute =
  AppCommunityTemplatesTemplateIdRouteImport.update({
    id: '/app/community/templates/$templateId',
    path: '/app/community/templates/$templateId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppCommunityMembersCommunityIdRoute =
  AppCommunityMembersCommunityIdRouteImport.update({
    id: '/app/community/members/$communityId',
    path: '/app/community/members/$communityId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppCommunityGoalsCommunityIdRoute =
  AppCommunityGoalsCommunityIdRouteImport.update({
    id: '/app/community/goals/$communityId',
    path: '/app/community/goals/$communityId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppCommunityActivityCommunityIdRoute =
  AppCommunityActivityCommunityIdRouteImport.update({
    id: '/app/community/activity/$communityId',
    path: '/app/community/activity/$communityId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievement-simulator': typeof AchievementSimulatorRoute
  '/achievements': typeof AchievementsRoute
  '/notifications': typeof NotificationsRoute
  '/app/communities': typeof AppCommunitiesRouteWithChildren
  '/app/goal': typeof AppGoalRoute
  '/app/home': typeof AppHomeRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/legal': typeof AppLegalRoute
  '/app/profile': typeof AppProfileRoute
  '/app/rewards': typeof AppRewardsRoute
  '/app/rewind': typeof AppRewindRoute
  '/app/rewind-history': typeof AppRewindHistoryRoute
  '/app/wellness': typeof AppWellnessRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/journal/$date': typeof JournalDateRoute
  '/chill/': typeof ChillIndexRoute
  '/goal/': typeof GoalIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/app/actions/flexx': typeof AppActionsFlexxRoute
  '/app/admin/feature-flags': typeof AppAdminFeatureFlagsRoute
  '/app/communities/my': typeof AppCommunitiesMyRoute
  '/app/community/$communityId': typeof AppCommunityCommunityIdRoute
  '/app/invite/$code': typeof AppInviteCodeRoute
  '/app/sub-profile/insights': typeof AppSubProfileInsightsRoute
  '/app/sub-profile/settings': typeof AppSubProfileSettingsRoute
  '/app/u/$username': typeof AppUUsernameRoute
  '/app/community/activity/$communityId': typeof AppCommunityActivityCommunityIdRoute
  '/app/community/goals/$communityId': typeof AppCommunityGoalsCommunityIdRoute
  '/app/community/members/$communityId': typeof AppCommunityMembersCommunityIdRoute
  '/app/community/templates/$templateId': typeof AppCommunityTemplatesTemplateIdRoute
  '/chill/timer/$sessionId/$duration': typeof ChillTimerSessionIdDurationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievement-simulator': typeof AchievementSimulatorRoute
  '/achievements': typeof AchievementsRoute
  '/notifications': typeof NotificationsRoute
  '/app/communities': typeof AppCommunitiesRouteWithChildren
  '/app/goal': typeof AppGoalRoute
  '/app/home': typeof AppHomeRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/legal': typeof AppLegalRoute
  '/app/profile': typeof AppProfileRoute
  '/app/rewards': typeof AppRewardsRoute
  '/app/rewind': typeof AppRewindRoute
  '/app/rewind-history': typeof AppRewindHistoryRoute
  '/app/wellness': typeof AppWellnessRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/journal/$date': typeof JournalDateRoute
  '/chill': typeof ChillIndexRoute
  '/goal': typeof GoalIndexRoute
  '/journal': typeof JournalIndexRoute
  '/app/actions/flexx': typeof AppActionsFlexxRoute
  '/app/admin/feature-flags': typeof AppAdminFeatureFlagsRoute
  '/app/communities/my': typeof AppCommunitiesMyRoute
  '/app/community/$communityId': typeof AppCommunityCommunityIdRoute
  '/app/invite/$code': typeof AppInviteCodeRoute
  '/app/sub-profile/insights': typeof AppSubProfileInsightsRoute
  '/app/sub-profile/settings': typeof AppSubProfileSettingsRoute
  '/app/u/$username': typeof AppUUsernameRoute
  '/app/community/activity/$communityId': typeof AppCommunityActivityCommunityIdRoute
  '/app/community/goals/$communityId': typeof AppCommunityGoalsCommunityIdRoute
  '/app/community/members/$communityId': typeof AppCommunityMembersCommunityIdRoute
  '/app/community/templates/$templateId': typeof AppCommunityTemplatesTemplateIdRoute
  '/chill/timer/$sessionId/$duration': typeof ChillTimerSessionIdDurationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievement-simulator': typeof AchievementSimulatorRoute
  '/achievements': typeof AchievementsRoute
  '/notifications': typeof NotificationsRoute
  '/app/communities': typeof AppCommunitiesRouteWithChildren
  '/app/goal': typeof AppGoalRoute
  '/app/home': typeof AppHomeRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/legal': typeof AppLegalRoute
  '/app/profile': typeof AppProfileRoute
  '/app/rewards': typeof AppRewardsRoute
  '/app/rewind': typeof AppRewindRoute
  '/app/rewind-history': typeof AppRewindHistoryRoute
  '/app/wellness': typeof AppWellnessRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/journal/$date': typeof JournalDateRoute
  '/chill/': typeof ChillIndexRoute
  '/goal/': typeof GoalIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/app/actions/flexx': typeof AppActionsFlexxRoute
  '/app/admin/feature-flags': typeof AppAdminFeatureFlagsRoute
  '/app/communities/my': typeof AppCommunitiesMyRoute
  '/app/community/$communityId': typeof AppCommunityCommunityIdRoute
  '/app/invite/$code': typeof AppInviteCodeRoute
  '/app/sub-profile/insights': typeof AppSubProfileInsightsRoute
  '/app/sub-profile/settings': typeof AppSubProfileSettingsRoute
  '/app/u/$username': typeof AppUUsernameRoute
  '/app/community/activity/$communityId': typeof AppCommunityActivityCommunityIdRoute
  '/app/community/goals/$communityId': typeof AppCommunityGoalsCommunityIdRoute
  '/app/community/members/$communityId': typeof AppCommunityMembersCommunityIdRoute
  '/app/community/templates/$templateId': typeof AppCommunityTemplatesTemplateIdRoute
  '/chill/timer/$sessionId/$duration': typeof ChillTimerSessionIdDurationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievement-simulator'
    | '/achievements'
    | '/notifications'
    | '/app/communities'
    | '/app/goal'
    | '/app/home'
    | '/app/insights'
    | '/app/legal'
    | '/app/profile'
    | '/app/rewards'
    | '/app/rewind'
    | '/app/rewind-history'
    | '/app/wellness'
    | '/auth/confirm'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/journal/$date'
    | '/chill/'
    | '/goal/'
    | '/journal/'
    | '/app/actions/flexx'
    | '/app/admin/feature-flags'
    | '/app/communities/my'
    | '/app/community/$communityId'
    | '/app/invite/$code'
    | '/app/sub-profile/insights'
    | '/app/sub-profile/settings'
    | '/app/u/$username'
    | '/app/community/activity/$communityId'
    | '/app/community/goals/$communityId'
    | '/app/community/members/$communityId'
    | '/app/community/templates/$templateId'
    | '/chill/timer/$sessionId/$duration'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievement-simulator'
    | '/achievements'
    | '/notifications'
    | '/app/communities'
    | '/app/goal'
    | '/app/home'
    | '/app/insights'
    | '/app/legal'
    | '/app/profile'
    | '/app/rewards'
    | '/app/rewind'
    | '/app/rewind-history'
    | '/app/wellness'
    | '/auth/confirm'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/journal/$date'
    | '/chill'
    | '/goal'
    | '/journal'
    | '/app/actions/flexx'
    | '/app/admin/feature-flags'
    | '/app/communities/my'
    | '/app/community/$communityId'
    | '/app/invite/$code'
    | '/app/sub-profile/insights'
    | '/app/sub-profile/settings'
    | '/app/u/$username'
    | '/app/community/activity/$communityId'
    | '/app/community/goals/$communityId'
    | '/app/community/members/$communityId'
    | '/app/community/templates/$templateId'
    | '/chill/timer/$sessionId/$duration'
  id:
    | '__root__'
    | '/'
    | '/achievement-simulator'
    | '/achievements'
    | '/notifications'
    | '/app/communities'
    | '/app/goal'
    | '/app/home'
    | '/app/insights'
    | '/app/legal'
    | '/app/profile'
    | '/app/rewards'
    | '/app/rewind'
    | '/app/rewind-history'
    | '/app/wellness'
    | '/auth/confirm'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/journal/$date'
    | '/chill/'
    | '/goal/'
    | '/journal/'
    | '/app/actions/flexx'
    | '/app/admin/feature-flags'
    | '/app/communities/my'
    | '/app/community/$communityId'
    | '/app/invite/$code'
    | '/app/sub-profile/insights'
    | '/app/sub-profile/settings'
    | '/app/u/$username'
    | '/app/community/activity/$communityId'
    | '/app/community/goals/$communityId'
    | '/app/community/members/$communityId'
    | '/app/community/templates/$templateId'
    | '/chill/timer/$sessionId/$duration'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementSimulatorRoute: typeof AchievementSimulatorRoute
  AchievementsRoute: typeof AchievementsRoute
  NotificationsRoute: typeof NotificationsRoute
  AppCommunitiesRoute: typeof AppCommunitiesRouteWithChildren
  AppGoalRoute: typeof AppGoalRoute
  AppHomeRoute: typeof AppHomeRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppLegalRoute: typeof AppLegalRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRewardsRoute: typeof AppRewardsRoute
  AppRewindRoute: typeof AppRewindRoute
  AppRewindHistoryRoute: typeof AppRewindHistoryRoute
  AppWellnessRoute: typeof AppWellnessRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  JournalDateRoute: typeof JournalDateRoute
  ChillIndexRoute: typeof ChillIndexRoute
  GoalIndexRoute: typeof GoalIndexRoute
  JournalIndexRoute: typeof JournalIndexRoute
  AppActionsFlexxRoute: typeof AppActionsFlexxRoute
  AppAdminFeatureFlagsRoute: typeof AppAdminFeatureFlagsRoute
  AppCommunityCommunityIdRoute: typeof AppCommunityCommunityIdRoute
  AppInviteCodeRoute: typeof AppInviteCodeRoute
  AppSubProfileInsightsRoute: typeof AppSubProfileInsightsRoute
  AppSubProfileSettingsRoute: typeof AppSubProfileSettingsRoute
  AppUUsernameRoute: typeof AppUUsernameRoute
  AppCommunityActivityCommunityIdRoute: typeof AppCommunityActivityCommunityIdRoute
  AppCommunityGoalsCommunityIdRoute: typeof AppCommunityGoalsCommunityIdRoute
  AppCommunityMembersCommunityIdRoute: typeof AppCommunityMembersCommunityIdRoute
  AppCommunityTemplatesTemplateIdRoute: typeof AppCommunityTemplatesTemplateIdRoute
  ChillTimerSessionIdDurationRoute: typeof ChillTimerSessionIdDurationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievement-simulator': {
      id: '/achievement-simulator'
      path: '/achievement-simulator'
      fullPath: '/achievement-simulator'
      preLoaderRoute: typeof AchievementSimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goal/': {
      id: '/goal/'
      path: '/goal'
      fullPath: '/goal/'
      preLoaderRoute: typeof GoalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chill/': {
      id: '/chill/'
      path: '/chill'
      fullPath: '/chill/'
      preLoaderRoute: typeof ChillIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$date': {
      id: '/journal/$date'
      path: '/journal/$date'
      fullPath: '/journal/$date'
      preLoaderRoute: typeof JournalDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/wellness': {
      id: '/app/wellness'
      path: '/app/wellness'
      fullPath: '/app/wellness'
      preLoaderRoute: typeof AppWellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/rewind-history': {
      id: '/app/rewind-history'
      path: '/app/rewind-history'
      fullPath: '/app/rewind-history'
      preLoaderRoute: typeof AppRewindHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/rewind': {
      id: '/app/rewind'
      path: '/app/rewind'
      fullPath: '/app/rewind'
      preLoaderRoute: typeof AppRewindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/rewards': {
      id: '/app/rewards'
      path: '/app/rewards'
      fullPath: '/app/rewards'
      preLoaderRoute: typeof AppRewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/legal': {
      id: '/app/legal'
      path: '/app/legal'
      fullPath: '/app/legal'
      preLoaderRoute: typeof AppLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/insights': {
      id: '/app/insights'
      path: '/app/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/home': {
      id: '/app/home'
      path: '/app/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/goal': {
      id: '/app/goal'
      path: '/app/goal'
      fullPath: '/app/goal'
      preLoaderRoute: typeof AppGoalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/communities': {
      id: '/app/communities'
      path: '/app/communities'
      fullPath: '/app/communities'
      preLoaderRoute: typeof AppCommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/u/$username': {
      id: '/app/u/$username'
      path: '/app/u/$username'
      fullPath: '/app/u/$username'
      preLoaderRoute: typeof AppUUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/sub-profile/settings': {
      id: '/app/sub-profile/settings'
      path: '/app/sub-profile/settings'
      fullPath: '/app/sub-profile/settings'
      preLoaderRoute: typeof AppSubProfileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/sub-profile/insights': {
      id: '/app/sub-profile/insights'
      path: '/app/sub-profile/insights'
      fullPath: '/app/sub-profile/insights'
      preLoaderRoute: typeof AppSubProfileInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/invite/$code': {
      id: '/app/invite/$code'
      path: '/app/invite/$code'
      fullPath: '/app/invite/$code'
      preLoaderRoute: typeof AppInviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/community/$communityId': {
      id: '/app/community/$communityId'
      path: '/app/community/$communityId'
      fullPath: '/app/community/$communityId'
      preLoaderRoute: typeof AppCommunityCommunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/communities/my': {
      id: '/app/communities/my'
      path: '/my'
      fullPath: '/app/communities/my'
      preLoaderRoute: typeof AppCommunitiesMyRouteImport
      parentRoute: typeof AppCommunitiesRoute
    }
    '/app/admin/feature-flags': {
      id: '/app/admin/feature-flags'
      path: '/app/admin/feature-flags'
      fullPath: '/app/admin/feature-flags'
      preLoaderRoute: typeof AppAdminFeatureFlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/actions/flexx': {
      id: '/app/actions/flexx'
      path: '/app/actions/flexx'
      fullPath: '/app/actions/flexx'
      preLoaderRoute: typeof AppActionsFlexxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chill/timer/$sessionId/$duration': {
      id: '/chill/timer/$sessionId/$duration'
      path: '/chill/timer/$sessionId/$duration'
      fullPath: '/chill/timer/$sessionId/$duration'
      preLoaderRoute: typeof ChillTimerSessionIdDurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/community/templates/$templateId': {
      id: '/app/community/templates/$templateId'
      path: '/app/community/templates/$templateId'
      fullPath: '/app/community/templates/$templateId'
      preLoaderRoute: typeof AppCommunityTemplatesTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/community/members/$communityId': {
      id: '/app/community/members/$communityId'
      path: '/app/community/members/$communityId'
      fullPath: '/app/community/members/$communityId'
      preLoaderRoute: typeof AppCommunityMembersCommunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/community/goals/$communityId': {
      id: '/app/community/goals/$communityId'
      path: '/app/community/goals/$communityId'
      fullPath: '/app/community/goals/$communityId'
      preLoaderRoute: typeof AppCommunityGoalsCommunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/community/activity/$communityId': {
      id: '/app/community/activity/$communityId'
      path: '/app/community/activity/$communityId'
      fullPath: '/app/community/activity/$communityId'
      preLoaderRoute: typeof AppCommunityActivityCommunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppCommunitiesRouteChildren {
  AppCommunitiesMyRoute: typeof AppCommunitiesMyRoute
}

const AppCommunitiesRouteChildren: AppCommunitiesRouteChildren = {
  AppCommunitiesMyRoute: AppCommunitiesMyRoute,
}

const AppCommunitiesRouteWithChildren = AppCommunitiesRoute._addFileChildren(
  AppCommunitiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementSimulatorRoute: AchievementSimulatorRoute,
  AchievementsRoute: AchievementsRoute,
  NotificationsRoute: NotificationsRoute,
  AppCommunitiesRoute: AppCommunitiesRouteWithChildren,
  AppGoalRoute: AppGoalRoute,
  AppHomeRoute: AppHomeRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppLegalRoute: AppLegalRoute,
  AppProfileRoute: AppProfileRoute,
  AppRewardsRoute: AppRewardsRoute,
  AppRewindRoute: AppRewindRoute,
  AppRewindHistoryRoute: AppRewindHistoryRoute,
  AppWellnessRoute: AppWellnessRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  JournalDateRoute: JournalDateRoute,
  ChillIndexRoute: ChillIndexRoute,
  GoalIndexRoute: GoalIndexRoute,
  JournalIndexRoute: JournalIndexRoute,
  AppActionsFlexxRoute: AppActionsFlexxRoute,
  AppAdminFeatureFlagsRoute: AppAdminFeatureFlagsRoute,
  AppCommunityCommunityIdRoute: AppCommunityCommunityIdRoute,
  AppInviteCodeRoute: AppInviteCodeRoute,
  AppSubProfileInsightsRoute: AppSubProfileInsightsRoute,
  AppSubProfileSettingsRoute: AppSubProfileSettingsRoute,
  AppUUsernameRoute: AppUUsernameRoute,
  AppCommunityActivityCommunityIdRoute: AppCommunityActivityCommunityIdRoute,
  AppCommunityGoalsCommunityIdRoute: AppCommunityGoalsCommunityIdRoute,
  AppCommunityMembersCommunityIdRoute: AppCommunityMembersCommunityIdRoute,
  AppCommunityTemplatesTemplateIdRoute: AppCommunityTemplatesTemplateIdRoute,
  ChillTimerSessionIdDurationRoute: ChillTimerSessionIdDurationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
